spring:
  profiles:
    active: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: BidIt

access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}

logging:
  level:
    org.springframework.security: DEBUG
